<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppShell from '@/components/AppShell.vue'
import { contractApi, type ClauseForm, type ClauseItem, type ContractDetail, type ContractVersion, type MemberOption, type CompletionCheck } from '@/api/contracts'
import { aiApi, type AiStatus, type AiFinding, type ContractAnswer } from '@/api/ai'

const route = useRoute()
const router = useRouter()
const contractId = Number(route.params.id)
const detail = ref<ContractDetail | null>(null)
const aiStatus = ref<AiStatus | null>(null)
const findings=ref<AiFinding[]>([]);const versions=ref<ContractVersion[]>([]);const members=ref<MemberOption[]>([]);const completion=ref<CompletionCheck|null>(null)
const loading = ref(true)
const saving = ref(false)
const error = ref('')
const message = ref('')
const activeTab = ref(route.query.tab === 'clauses' ? 'clauses' : 'overview')
const editorOpen = ref(false)
const editingId = ref<number | null>(null)
const editingFindingId=ref<number|null>(null)
const question=ref('');const answer=ref<ContractAnswer|null>(null);const versionFile=ref<File|null>(null);const versionSummary=ref('');const versionReviewer=ref<number>();const lifecycleReason=ref('')
const form = reactive<ClauseForm>({ clauseType: 'PAYMENT', clauseTitle: '', clauseContent: '', sourcePageNo: 1, sourceExcerpt: '' })
const labels: Record<string, string> = { PAYMENT: '付款', DELIVERY: '交付', ACCEPTANCE: '验收', INVOICE: '开票', RENEWAL: '续签', OTHER: '其他' }
const confirmedCount = computed(() => detail.value?.clauses.filter(item => item.confirmationStatus === 'CONFIRMED').length ?? 0)
const allConfirmed = computed(() => !!detail.value?.clauses.length && confirmedCount.value === detail.value.clauses.length)
const statusLabel: Record<string, string> = { DRAFT: '草稿', TERMS_CONFIRMED: '条款已确认', ACTIVE: '履约中', COMPLETED: '已完成' }

async function load() { loading.value = true; error.value = ''; try { [detail.value, aiStatus.value,findings.value,versions.value,members.value,completion.value] = await Promise.all([contractApi.detail(contractId), aiApi.status(),aiApi.findings(contractId),contractApi.versions(contractId),contractApi.activeMembers(),contractApi.completionCheck(contractId)]) } catch (cause) { error.value = cause instanceof Error ? cause.message : '合同详情加载失败' } finally { loading.value = false } }
async function perform(action: () => Promise<unknown>, successMessage: string) { saving.value = true; error.value = ''; message.value = ''; try { const result=await action();if(result&&typeof result==='object'&&'clauses' in result)detail.value=result as ContractDetail; message.value = successMessage } catch (cause) { error.value = cause instanceof Error ? cause.message : '操作失败' } finally { saving.value = false } }
function openCreate() { editingId.value = null;editingFindingId.value=null; Object.assign(form, { clauseType: 'PAYMENT', clauseTitle: '', clauseContent: '', sourcePageNo: 1, sourceExcerpt: '' }); editorOpen.value = true }
function editClause(clause: ClauseItem) { editingId.value = clause.id; Object.assign(form, { clauseType: clause.clauseType, clauseTitle: clause.clauseTitle, clauseContent: clause.clauseContent, sourcePageNo: clause.sourcePageNo, sourceExcerpt: clause.sourceExcerpt ?? '' }); editorOpen.value = true }
function editFinding(item:AiFinding){editingId.value=null;editingFindingId.value=item.id;Object.assign(form,{clauseType:item.findingType,clauseTitle:item.title,clauseContent:item.content,sourcePageNo:item.sourcePageNo??1,sourceExcerpt:item.sourceExcerpt??''});editorOpen.value=true}
async function saveClause(confirmAfterSave = false) {
  saving.value = true; error.value = ''; message.value = ''
  try {
    const result = editingId.value ? await contractApi.updateClause(contractId, editingId.value, form) : await contractApi.createClause(contractId, form)
    const savedId = editingId.value ?? result.clauses[result.clauses.length - 1]?.id
    detail.value = confirmAfterSave && savedId ? await contractApi.confirmClause(contractId, savedId) : result
    message.value = confirmAfterSave ? '条款已保存并完成人工确认。' : '条款已保存，仍需显式人工确认。'
    editorOpen.value = false
  } catch (cause) { error.value = cause instanceof Error ? cause.message : '条款保存失败' }
  finally { saving.value = false }
}
async function startManualReview() { await perform(() => contractApi.prepareParse(contractId), '已进入人工审阅模式。'); activeTab.value = 'clauses' }
async function startAiReview() { saving.value = true; error.value = ''; message.value = ''; try { await aiApi.requestParse(contractId); message.value = 'AI 解析任务已提交，完成后会发送站内通知。'; await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'AI 解析任务提交失败' } finally { saving.value = false } }
async function saveFinding(){if(!editingFindingId.value)return;saving.value=true;try{findings.value=await aiApi.updateFinding(contractId,editingFindingId.value,{findingType:form.clauseType,title:form.clauseTitle,content:form.clauseContent,sourcePageNo:form.sourcePageNo,sourceExcerpt:form.sourceExcerpt});message.value='AI 提取项已人工修改，仍需确认。';editorOpen.value=false}catch(cause){error.value=cause instanceof Error?cause.message:'修改失败'}finally{saving.value=false}}
async function askAi(){if(!question.value.trim())return;saving.value=true;try{answer.value=await aiApi.ask(contractId,question.value)}catch(cause){error.value=cause instanceof Error?cause.message:'问答失败'}finally{saving.value=false}}
function selectVersionFile(e:Event){versionFile.value=(e.target as HTMLInputElement).files?.[0]??null}
async function uploadVersion(){if(!versionFile.value||!versionSummary.value.trim()||!versionReviewer.value){error.value='请选择文件、填写变更摘要并指定审核人';return}await perform(()=>contractApi.uploadVersion(contractId,versionFile.value!,versionSummary.value,versionReviewer.value!),'候选版本已提交审核。') ;await load()}
async function lifecycle(action:'complete'|'terminate'|'archive'|'unarchive'){await perform(()=>contractApi.lifecycle(contractId,action,lifecycleReason.value),`合同操作 ${action} 已完成。`);await load()}
async function generateTasks() { saving.value = true; error.value = ''; try { await contractApi.generateTaskDrafts(contractId); await router.push('/tasks') } catch (cause) { error.value = cause instanceof Error ? cause.message : '任务草稿生成失败' } finally { saving.value = false } }
onMounted(load)
</script>

<template>
  <AppShell :title="detail ? `${detail.contractNo} ${detail.name}` : '合同详情'" subtitle="合同详情与条款审阅">
    <template #actions><button class="secondary-button compact" @click="router.push('/contracts')">← 返回列表</button></template>
    <p v-if="error" class="feedback error">{{ error }}</p><p v-if="message" class="feedback success">{{ message }}</p>
    <div v-if="loading" class="loading-state panel-card">正在加载合同详情…</div>
    <template v-else-if="detail">
      <section class="contract-hero">
        <div><h2>{{ detail.name }}</h2><p>编号 {{ detail.contractNo }} · 相对方：{{ detail.counterpartyName }} · 原文件：{{ detail.sourceFilename ?? '无附件' }}</p></div>
        <button class="secondary-button" @click="contractApi.downloadSource(detail)">下载原合同</button>
        <div class="contract-facts"><span><small>合同总额</small><strong>¥{{ Number(detail.totalAmount).toLocaleString('zh-CN') }}</strong></span><span><small>业务状态</small><strong><i class="status-badge" :class="detail.businessStatus.toLowerCase()">{{ statusLabel[detail.businessStatus] ?? detail.businessStatus }}</i></strong></span><span><small>归档状态</small><strong>{{ detail.archiveStatus === 'ARCHIVED' ? '已归档' : '未归档' }}</strong></span><span><small>审阅方式</small><strong>{{ aiStatus?.configured ? 'AI 辅助 + 人工确认' : '人工审阅' }}</strong></span></div>
      </section>

      <nav class="detail-tabs"><button :class="{ active: activeTab === 'overview' }" @click="activeTab = 'overview'">概览</button><button :class="{ active: activeTab === 'clauses' }" @click="activeTab = 'clauses'">关键条款 <span>{{ detail.clauses.length }}</span></button><button :class="{active:activeTab==='ai'}" @click="activeTab='ai'">AI 审阅与问答 <span>{{findings.length}}</span></button><button :class="{active:activeTab==='versions'}" @click="activeTab='versions'">版本与结项</button><button @click="router.push({ path: '/tasks', query: { contractId } })">履约任务</button><button @click="router.push({ path: '/receivables', query: { contractId } })">财务与风险</button></nav>

      <section v-if="activeTab === 'overview'" class="detail-overview-grid">
        <article class="panel-card"><div class="panel-heading"><div><h3>合同审阅进度</h3><p>{{ aiStatus?.configured ? 'AI 先提取关键节点，再由企业人员逐项确认' : '当前未配置模型，使用人工审阅且不生成虚假结果' }}</p></div><span class="status-badge" :class="detail.parseJob ? 'terms_confirmed' : 'draft'">{{ detail.parseJob?.jobStatus === 'QUEUED' || detail.parseJob?.jobStatus === 'PROCESSING' ? 'AI 解析中' : detail.parseJob ? (aiStatus?.configured ? '待人工确认' : '人工审阅模式') : '尚未开始' }}</span></div><div class="review-progress"><div><i :style="{ width: `${detail.clauses.length ? confirmedCount / detail.clauses.length * 100 : 0}%` }"></i></div><p><span>已确认 {{ confirmedCount }} / {{ detail.clauses.length }} 项</span><strong>{{ allConfirmed ? '可发布' : '待补充或确认' }}</strong></p></div><p class="ai-config-note">{{ aiStatus?.boundary }}</p><div class="inline-actions"><button v-if="aiStatus?.configured && !detail.parseJob" class="primary-button" :disabled="saving" @click="startAiReview">发起 AI 辅助解析</button><button v-if="!detail.parseJob" class="secondary-button" :disabled="saving" @click="startManualReview">开始人工审阅</button><button v-else class="primary-button" @click="activeTab = 'clauses'">继续条款审阅</button></div></article>
        <article class="panel-card"><div class="panel-heading"><div><h3>履约任务</h3><p>由已人工确认的关键条款生成</p></div></div><div class="milestone-note"><span>✓</span><div><strong>{{ detail.businessStatus === 'TERMS_CONFIRMED' ? '条款已发布，可生成任务' : '等待条款审阅完成' }}</strong><p>任务生成后由执行人领取并指定不同成员作为审核人。</p></div></div><button v-if="detail.businessStatus === 'TERMS_CONFIRMED'" class="primary-button" :disabled="saving" @click="generateTasks">生成履约任务草稿</button></article>
      </section>

      <section v-else-if="activeTab==='clauses'" class="clause-review-layout">
        <aside class="source-panel"><div class="section-title"><h3>合同原文与来源</h3><p>{{ detail.sourceFilename }}</p></div><div v-if="!detail.clauses.length" class="empty-state"><span>文</span><h3>尚无来源定位</h3><p>人工录入条款时，请同时填写页码和原文摘录。</p></div><button v-for="clause in detail.clauses" :key="clause.id" class="source-excerpt" @click="editClause(clause)"><b>P{{ clause.sourcePageNo }}</b><span><strong>{{ clause.clauseTitle }}</strong><small>{{ clause.sourceExcerpt || clause.clauseContent }}</small></span></button><p class="source-footnote">DOCX 无稳定页码时，可使用段落序号作为定位依据。</p></aside>
        <section class="result-panel"><div class="review-toolbar"><div><h3>条款审阅与人工确认</h3><p>{{ detail.clauses.length - confirmedCount }} 项待确认 · {{ confirmedCount }} 项已确认</p></div><button class="secondary-button" @click="openCreate">＋ 人工补录</button></div><div class="manual-review-banner"><strong>人工审阅模式</strong><span>所有结果均需人工确认；系统不会将辅助分析描述为法律意见。</span></div><div v-if="!detail.parseJob" class="empty-state large-empty"><span>审</span><h3>尚未开始审阅</h3><p>先创建人工审阅准备，再录入需要跟踪的付款、交付、验收或开票条款。</p><button class="primary-button" @click="startManualReview">开始人工审阅</button></div><div v-else-if="!detail.clauses.length" class="empty-state large-empty"><span>＋</span><h3>还没有关键条款</h3><p>从原合同中录入第一条可执行条款，并保留来源页码和原文。</p><button class="primary-button" @click="openCreate">录入第一条条款</button></div><article v-for="clause in detail.clauses" v-else :key="clause.id" class="result-card"><div class="result-card-head"><div><span class="clause-type">{{ labels[clause.clauseType] ?? clause.clauseType }}</span><span class="status-badge" :class="clause.confirmationStatus === 'CONFIRMED' ? 'terms_confirmed' : 'draft'">{{ clause.confirmationStatus === 'CONFIRMED' ? '已人工确认' : '待确认' }}</span></div><button class="text-button" @click="editClause(clause)">修改</button></div><h4>{{ clause.clauseTitle }}</h4><p>{{ clause.clauseContent }}</p><small>来源：P{{ clause.sourcePageNo }} · {{ clause.sourceExcerpt || '未填写原文摘录' }}</small><div v-if="clause.confirmationStatus !== 'CONFIRMED'" class="result-actions"><button class="secondary-button" @click="editClause(clause)">修改</button><button class="primary-button" :disabled="saving" @click="perform(() => contractApi.confirmClause(contractId, clause.id), '条款已人工确认。')">人工确认</button></div></article><footer v-if="detail.parseJob" class="review-footer"><span>{{ allConfirmed ? '全部条款已确认，可以发布。' : '可保存未完成审阅，但全部确认前不能发布。' }}</span><button class="primary-button" :disabled="saving || !allConfirmed || detail.businessStatus === 'TERMS_CONFIRMED'" @click="perform(() => contractApi.publishTerms(contractId), '已发布人工确认条款。')">{{ detail.businessStatus === 'TERMS_CONFIRMED' ? '已发布' : '发布确认条款' }}</button></footer></section>
      </section>

      <section v-else-if="activeTab==='ai'" class="detail-overview-grid ai-workspace">
        <article class="panel-card"><div class="panel-heading"><div><h3>AI 结构化提取项</h3><p>修改、确认或驳回后才进入正式合同条款</p></div><span class="status-badge" :class="aiStatus?.configured?'terms_confirmed':'draft'">{{aiStatus?.configured?'真实模型已配置':'人工模式'}}</span></div><div v-if="!findings.length" class="empty-state"><span>AI</span><h3>暂无提取结果</h3><p>{{aiStatus?.configured?'可从概览发起解析，完成后在此人工审阅。':'配置模型后才能产生真实提取结果。'}}</p></div><article v-for="item in findings" :key="item.id" class="result-card"><div class="result-card-head"><div><span class="clause-type">{{labels[item.findingType]??item.findingType}}</span><span class="status-badge" :class="item.reviewStatus==='CONFIRMED'?'terms_confirmed':'draft'">{{item.reviewStatus}}</span></div><button v-if="item.reviewStatus==='PENDING_CONFIRMATION'" class="text-button" @click="editFinding(item)">修改</button></div><h4>{{item.title}}</h4><p>{{item.content}}</p><small>来源：{{item.sourcePageNo?`P${item.sourcePageNo}`:'待人工定位'}} · 置信度 {{item.confidence??'—'}}</small><div v-if="item.reviewStatus==='PENDING_CONFIRMATION'" class="result-actions"><button class="secondary-button danger" @click="perform(()=>aiApi.rejectFinding(contractId,item.id,'人工判定不采纳'),'提取项已驳回。').then(load)">驳回</button><button class="primary-button" @click="perform(()=>aiApi.confirmFinding(contractId,item.id),'已确认并转为正式条款。').then(load)">人工确认</button></div></article></article>
        <article class="panel-card ai-question-card"><div class="panel-heading"><div><h3>合同 AI 助手</h3><p>向量检索当前授权合同，并由模型按需调用只读业务工具</p></div></div><textarea v-model="question" rows="4" placeholder="例如：下一笔付款节点是什么？目前有哪些未完成任务？"></textarea><button class="primary-button" :disabled="saving||!aiStatus?.configured" @click="askAi">向当前合同提问</button><div v-if="answer" class="ai-answer"><strong>辅助回答</strong><p>{{answer.answer}}</p><small>检索：{{answer.retrievalMode}} · 工具：{{answer.toolsUsed.length?answer.toolsUsed.join('、'):'未调用'}} · {{answer.modelName}}</small><small v-if="answer.warning">{{answer.warning}}</small><details v-if="answer.ragSources.length"><summary>查看合同原文依据（{{answer.ragSources.length}}）</summary><blockquote v-for="source in answer.ragSources" :key="source.chunkIndex"><b>{{source.pageNo?`第 ${source.pageNo} 页`:'页码未知'}} · Chunk {{source.chunkIndex}}</b><p>{{source.sourceText}}</p></blockquote></details><em>{{answer.boundary}}</em></div></article>
      </section>

      <section v-else class="detail-overview-grid version-workspace">
        <article class="panel-card"><div class="panel-heading"><div><h3>合同版本</h3><p>候选版本需由另一名企业管理员或法务确认</p></div></div><div class="version-upload"><input type="file" accept=".pdf,.docx" @change="selectVersionFile"><input v-model="versionSummary" placeholder="版本变更摘要"><select v-model="versionReviewer"><option :value="undefined">选择审核人</option><option v-for="m in members" :key="m.membershipId" :value="m.membershipId">{{m.displayName}}</option></select><button class="primary-button" @click="uploadVersion">提交候选版本</button></div><article v-for="v in versions" :key="v.id" class="version-item"><div><strong>V{{v.versionNo}} · {{v.originalFilename}}</strong><small>{{v.changeSummary||'初始版本'}}</small></div><span class="status-badge" :class="v.versionStatus==='ACTIVE'?'terms_confirmed':'draft'">{{v.versionStatus}}</span><div v-if="v.requestStatus==='PENDING'" class="inline-actions"><button class="secondary-button danger" @click="perform(()=>contractApi.reviewVersion(contractId,v.changeRequestId!,false,'版本变更不通过'),'版本已驳回。').then(load)">驳回</button><button class="primary-button" @click="perform(()=>contractApi.reviewVersion(contractId,v.changeRequestId!,true,'已核对变更摘要'),'版本已批准。').then(load)">批准</button></div></article></article>
        <article class="panel-card"><div class="panel-heading"><div><h3>完成、终止与归档</h3><p>状态检查通过后执行，归档生成不可变快照</p></div></div><dl v-if="completion" class="task-meta"><div><dt>未完成任务</dt><dd>{{completion.unfinishedTaskCount}}</dd></div><div><dt>待审核</dt><dd>{{completion.pendingReviewCount}}</dd></div><div><dt>活动风险</dt><dd>{{completion.activeRiskCount}}</dd></div><div><dt>未清应收</dt><dd>{{completion.receivableBalance==null?'无权限':'¥'+completion.receivableBalance}}</dd></div></dl><label>操作原因<input v-model="lifecycleReason" placeholder="终止、归档或解档时必填"></label><div class="lifecycle-actions"><button class="primary-button" :disabled="!completion?.completable" @click="lifecycle('complete')">标记完成</button><button class="secondary-button danger" @click="lifecycle('terminate')">终止合同</button><button v-if="detail.archiveStatus!=='ARCHIVED'" class="secondary-button" @click="lifecycle('archive')">归档</button><button v-else class="secondary-button" @click="lifecycle('unarchive')">解档</button></div></article>
      </section>

      <div v-if="editorOpen" class="drawer-backdrop" @click.self="editorOpen = false"><aside class="upload-drawer clause-editor"><div class="drawer-heading"><div><h2>{{ editingFindingId ? '修改 AI 提取项' : editingId ? '修改结果项' : '人工补录条款' }}</h2><p>保存修改后仍需显式确认才生效</p></div><button class="icon-button" @click="editorOpen = false">×</button></div><form @submit.prevent="editingFindingId?saveFinding():saveClause(false)"><label>节点类型 <em>*</em><select v-model="form.clauseType"><option v-for="(label, key) in labels" :key="key" :value="key">{{ label }}</option></select></label><label>条款标题 <em>*</em><input v-model.trim="form.clauseTitle" required /></label><label>条款内容 <em>*</em><textarea v-model.trim="form.clauseContent" rows="5" required /></label><label>原文页码 <em>*</em><input v-model.number="form.sourcePageNo" type="number" min="1" required /></label><label>原文摘录<textarea v-model.trim="form.sourceExcerpt" rows="4" placeholder="粘贴对应合同原文，便于追溯" /></label><div class="drawer-actions"><button type="button" class="secondary-button" @click="editorOpen = false">取消</button><button class="secondary-button" :disabled="saving">保存修改</button><button v-if="!editingFindingId" type="button" class="primary-button" :disabled="saving" @click="saveClause(true)">保存并确认</button></div></form></aside></div>
    </template>
  </AppShell>
</template>
