<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppShell from '@/components/AppShell.vue'
import { contractApi, type ContractItem, type MemberOption } from '@/api/contracts'
import { financeApi, type ReceivableItem, type RiskItem } from '@/api/finance'

const route=useRoute(),router=useRouter()
const isRisk=computed(()=>route.path==='/risks')
const receivables=ref<ReceivableItem[]>([]),risks=ref<RiskItem[]>([]),contracts=ref<ContractItem[]>([]),members=ref<MemberOption[]>([])
const loading=ref(true),saving=ref(false),error=ref(''),message=ref(''),riskFilter=ref('ALL')
const riskActionMode=ref<'IN_PROGRESS'|'IGNORED'|null>(null)
const drawer=ref<'plan'|'receipt'|'invoice'|'risk'|null>(null),selectedPlan=ref<ReceivableItem|null>(null),selectedRisk=ref<RiskItem|null>(null)
const today=new Date().toISOString().slice(0,10),reviewDefault=new Date(Date.now()+7*86400000).toISOString().slice(0,10)
const contractFilter=computed(()=>Number(route.query.contractId)||null)
const planForm=reactive({contractId:0,planName:'',planAmount:0,triggerStatus:'TRIGGERED',dueDate:''})
const receiptForm=reactive({amount:0,receiptDate:today,paymentMethod:'BANK_TRANSFER',payerName:'',referenceNo:'',note:''})
const invoiceForm=reactive({invoiceNo:'',amount:0,invoiceDate:today,invoiceType:'VAT_SPECIAL',invoiceTitle:''})
const riskForm=reactive({handlerMembershipId:0,handlingPlan:'',reason:'',reviewDate:reviewDefault})
const money=new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0})
const visibleReceivables=computed(()=>contractFilter.value?receivables.value.filter(v=>v.contractId===contractFilter.value):receivables.value)
const totals=computed(()=>visibleReceivables.value.reduce((a,v)=>({plan:a.plan+Number(v.planAmount),received:a.received+Number(v.receivedAmount),balance:a.balance+Number(v.balance),overdue:a.overdue+Number(v.overdueAmount)}),{plan:0,received:0,balance:0,overdue:0}))
const riskTabs=computed(()=>{const scoped=risks.value.filter(r=>!contractFilter.value||r.contractId===contractFilter.value);return [{value:'ALL',label:'全部',count:scoped.length},...['NEW','ACKNOWLEDGED','IN_PROGRESS','PENDING_CLOSE','CLOSED','IGNORED'].map(v=>({value:v,label:riskStatus[v],count:scoped.filter(r=>r.riskStatus===v).length}))]})
const visibleRisks=computed(()=>risks.value.filter(r=>(!contractFilter.value||r.contractId===contractFilter.value)&&(riskFilter.value==='ALL'||r.riskStatus===riskFilter.value)))
const invoiceLabel:Record<string,string>={UNINVOICED:'未开票',PARTIALLY_INVOICED:'部分开票',INVOICED:'已开票'}
const collectionLabel:Record<string,string>={UNPAID:'未回款',PARTIALLY_PAID:'部分回款',PAID:'已回款'}
const dueLabel:Record<string,string>={PENDING_TRIGGER:'待触发',NOT_DUE:'未到期',DUE_TODAY:'今日到期',OVERDUE:'已逾期',SETTLED:'已结清'}
const riskStatus:Record<string,string>={NEW:'新建',ACKNOWLEDGED:'已确认',IN_PROGRESS:'处理中',PENDING_CLOSE:'待结案',CLOSED:'已解决',IGNORED:'已忽略'}

async function load(){loading.value=true;error.value='';try{if(isRisk.value){[risks.value,members.value]=await Promise.all([financeApi.listRisks(),contractApi.activeMembers()])}else{[receivables.value,contracts.value,risks.value]=await Promise.all([financeApi.listReceivables(),contractApi.list(),financeApi.listRisks()])}}catch(c){error.value=c instanceof Error?c.message:'数据加载失败'}finally{loading.value=false}}
async function perform(action:()=>Promise<unknown>,success:string){saving.value=true;error.value='';message.value='';try{await action();message.value=success;drawer.value=null;await load()}catch(c){error.value=c instanceof Error?c.message:'操作失败'}finally{saving.value=false}}
function openPlan(){Object.assign(planForm,{contractId:contractFilter.value??contracts.value[0]?.id??0,planName:'',planAmount:0,triggerStatus:'TRIGGERED',dueDate:''});drawer.value='plan'}
function openReceipt(p:ReceivableItem){selectedPlan.value=p;Object.assign(receiptForm,{amount:Number(p.balance),receiptDate:today,paymentMethod:'BANK_TRANSFER',payerName:p.counterpartyName,referenceNo:'',note:''});drawer.value='receipt'}
function openInvoice(p:ReceivableItem){selectedPlan.value=p;Object.assign(invoiceForm,{invoiceNo:'',amount:Number(p.planAmount)-Number(p.invoicedAmount),invoiceDate:today,invoiceType:'VAT_SPECIAL',invoiceTitle:p.counterpartyName});drawer.value='invoice'}
function openRisk(r:RiskItem){selectedRisk.value=r;riskActionMode.value=null;Object.assign(riskForm,{handlerMembershipId:r.handlerMembershipId??members.value[0]?.membershipId??0,handlingPlan:r.handlingPlan??'',reason:r.ignoredReason??'',reviewDate:r.reviewDate??reviewDefault});drawer.value='risk'}
function createPlan(){perform(()=>financeApi.createReceivable({contractId:Number(planForm.contractId),planName:planForm.planName,planAmount:Number(planForm.planAmount),triggerStatus:planForm.triggerStatus,dueDate:planForm.triggerStatus==='TRIGGERED'?planForm.dueDate:null}),'应收计划已创建并完成逾期重评。')}
function addReceipt(){if(!selectedPlan.value)return;perform(()=>financeApi.addReceipt(selectedPlan.value!.id,{...receiptForm,amount:Number(receiptForm.amount),requestKey:crypto.randomUUID()}),'回款已登记，余额和风险已更新。')}
function addInvoice(){if(!selectedPlan.value)return;perform(()=>financeApi.addInvoice(selectedPlan.value!.id,{...invoiceForm,amount:Number(invoiceForm.amount),requestKey:crypto.randomUUID()}),'已有发票已登记。')}
watch(()=>route.path,()=>{riskFilter.value='ALL';riskActionMode.value=null;drawer.value=null;load()})
onMounted(load)
</script>

<template>
 <AppShell :title="isRisk?'风险中心':'回款管理'" :subtitle="isRisk?'规则驱动，同一逾期事实只保留一条风险':'本企业作为收款方 · 人民币'">
  <template #actions><button v-if="!isRisk" class="primary-button compact" @click="openPlan">＋ 新建应收计划</button><button class="secondary-button compact" @click="load">↻ 刷新</button></template>
  <p v-if="error" class="feedback error">{{error}}</p><p v-if="message" class="feedback success">{{message}}</p>
  <nav class="finance-page-tabs"><button :class="{active:!isRisk}" @click="router.push({path:'/receivables',query:route.query})">回款台账</button><button :class="{active:isRisk}" @click="router.push({path:'/risks',query:route.query})">风险中心 <span>{{risks.filter(r=>(!contractFilter||r.contractId===contractFilter)&&!['CLOSED'].includes(r.riskStatus)).length||''}}</span></button><button v-if="contractFilter" class="context-back" @click="router.push(`/contracts/${contractFilter}`)">← 返回合同详情</button></nav>

  <template v-if="!isRisk">
   <section class="finance-metrics"><article><span>应收计划合计</span><strong>{{money.format(totals.plan)}}</strong></article><article><span>已收（有效流水合计）</span><strong class="green">{{money.format(totals.received)}}</strong></article><article><span>余额（含未触发）</span><strong>{{money.format(totals.balance)}}</strong></article><article><span>其中逾期余额</span><strong class="red">{{money.format(totals.overdue)}}</strong></article></section>
   <section class="contract-table-card"><div v-if="loading" class="loading-state">正在加载回款台账…</div><div v-else-if="!visibleReceivables.length" class="empty-state large-empty"><span>¥</span><h3>还没有应收计划</h3><p>从已人工确认的付款条款创建第一笔应收计划。</p><button class="primary-button" @click="openPlan">新建应收计划</button></div><div v-else class="table-scroll"><table class="contract-table finance-table"><thead><tr><th>应收计划</th><th>关联合同</th><th>开票</th><th>收款</th><th>到期</th><th>计划金额</th><th>已收</th><th>余额</th><th>逾期</th><th>操作</th></tr></thead><tbody><tr v-for="p in visibleReceivables" :key="p.id"><td><strong>{{p.planName}}</strong><small class="table-subline">{{p.dueDate?`到期 ${p.dueDate}`:'业务事件触发后计算'}}</small></td><td>{{p.contractNo}}<small class="table-subline">{{p.contractName}}</small></td><td><span class="ledger-state">{{invoiceLabel[p.invoiceStatus]}}</span></td><td><span class="ledger-state">{{collectionLabel[p.collectionStatus]}}</span></td><td><span class="status-badge" :class="p.dueStatus.toLowerCase()">{{dueLabel[p.dueStatus]}}</span></td><td>{{money.format(p.planAmount)}}</td><td>{{money.format(p.receivedAmount)}}</td><td>{{money.format(p.balance)}}</td><td :class="{overdue:p.overdueAmount>0}">{{p.overdueAmount?money.format(p.overdueAmount):'—'}}</td><td><div class="row-actions"><button v-if="p.balance>0" class="text-button" @click="openReceipt(p)">登记回款</button><button v-if="p.invoicedAmount<p.planAmount" class="text-button subtle" @click="openInvoice(p)">登记发票</button></div></td></tr></tbody></table></div></section>
   <p class="caliber-note">金额口径：开票、收款、到期为三个独立维度；余额＝计划金额−有效已收。待触发计划计入余额，但不计入逾期。</p>
  </template>

  <template v-else>
   <section class="filter-card risk-filter"><div class="status-tabs"><button v-for="t in riskTabs" :key="t.value" :class="{active:riskFilter===t.value}" @click="riskFilter=t.value">{{t.label}} <span>{{t.count}}</span></button></div><p class="scope-note">风险规则第一版只读；当前已启用“回款逾期”规则。</p></section>
   <section class="contract-table-card"><div v-if="loading" class="loading-state">正在执行风险扫描…</div><div v-else-if="!visibleRisks.length" class="empty-state large-empty"><span>✓</span><h3>当前没有匹配的风险</h3><p>风险扫描不会为待触发应收生成虚假逾期。</p></div><div v-else class="table-scroll"><table class="contract-table"><thead><tr><th>规则</th><th>等级</th><th>关联对象</th><th>事实依据</th><th>处置状态</th><th>处理人</th><th>复查日</th><th>操作</th></tr></thead><tbody><tr v-for="r in visibleRisks" :key="r.id"><td>{{r.ruleCode==='RECEIVABLE_OVERDUE'?'回款逾期':r.ruleCode}}</td><td><span class="risk-level high">高</span></td><td>{{r.contractNo}} · 应收 #{{r.objectId}}</td><td class="fact-cell">{{r.factSummary}}</td><td><span class="status-badge" :class="r.riskStatus.toLowerCase()">{{riskStatus[r.riskStatus]}}</span></td><td>{{r.handlerName??'—'}}</td><td>{{r.reviewDate??'—'}}</td><td><button class="text-button" @click="openRisk(r)">{{r.riskStatus==='PENDING_CLOSE'?'结案':'处置'}}</button></td></tr></tbody></table></div></section>
   <p class="caliber-note">处置链路：新建 → 已确认 → 处理中；根因消除后进入待结案。忽略必须填写理由和复查日，且不会改变逾期事实与金额。</p>
  </template>

  <div v-if="drawer" class="drawer-backdrop" @click.self="drawer=null"><aside class="upload-drawer finance-drawer"><div class="drawer-heading"><div><h2>{{drawer==='plan'?'新建应收计划':drawer==='receipt'?'登记回款':drawer==='invoice'?'登记已有发票':'风险处置'}}</h2><p v-if="selectedPlan">{{selectedPlan.contractNo}} {{selectedPlan.contractName}} · {{selectedPlan.planName}}</p><p v-else-if="selectedRisk">{{selectedRisk.contractNo}} {{selectedRisk.contractName}}</p></div><button class="icon-button" @click="drawer=null">×</button></div>
   <form v-if="drawer==='plan'" @submit.prevent="createPlan"><label>关联合同 <em>*</em><select v-model="planForm.contractId" required><option v-for="c in contracts" :key="c.id" :value="c.id">{{c.contractNo}} {{c.name}}</option></select></label><label>计划名称 <em>*</em><input v-model.trim="planForm.planName" required placeholder="例如：一期应收" /></label><label>计划金额 <em>*</em><input v-model.number="planForm.planAmount" required type="number" min="0.01" step="0.01" /></label><label>触发状态 <em>*</em><select v-model="planForm.triggerStatus"><option value="TRIGGERED">已触发（固定到期日）</option><option value="PENDING_TRIGGER">待触发（暂无到期日）</option></select></label><label v-if="planForm.triggerStatus==='TRIGGERED'">到期日 <em>*</em><input v-model="planForm.dueDate" type="date" required /></label><div v-else class="manual-mode-note">待触发计划不填写到期日，也不会产生逾期风险。</div><div class="drawer-actions"><button type="button" class="secondary-button" @click="drawer=null">取消</button><button class="primary-button" :disabled="saving">确认创建</button></div></form>
   <form v-else-if="drawer==='receipt'&&selectedPlan" @submit.prevent="addReceipt"><div class="drawer-summary"><span>计划金额<strong>{{money.format(selectedPlan.planAmount)}}</strong></span><span>有效已收<strong>{{money.format(selectedPlan.receivedAmount)}}</strong></span><span>当前余额<strong>{{money.format(selectedPlan.balance)}}</strong></span></div><label>本次回款金额 <em>*</em><input v-model.number="receiptForm.amount" type="number" min="0.01" :max="selectedPlan.balance" step="0.01" required /></label><label>实际到账日期 <em>*</em><input v-model="receiptForm.receiptDate" type="date" :max="today" required /></label><label>收款方式 <em>*</em><select v-model="receiptForm.paymentMethod"><option value="BANK_TRANSFER">银行转账</option><option value="OTHER">其他</option></select></label><label>付款方 <em>*</em><input v-model.trim="receiptForm.payerName" required /></label><label>参考流水号<input v-model.trim="receiptForm.referenceNo" placeholder="辅助查重" /></label><label>备注<textarea v-model.trim="receiptForm.note" rows="3" /></label><div class="drawer-actions"><button type="button" class="secondary-button" @click="drawer=null">取消</button><button class="primary-button" :disabled="saving">确认登记</button></div></form>
   <form v-else-if="drawer==='invoice'&&selectedPlan" @submit.prevent="addInvoice"><div class="manual-review-banner"><strong>登记说明</strong><span>本功能用于登记已有发票，不是税务开票，平台不会实际开具发票。</span></div><label>发票编号 <em>*</em><input v-model.trim="invoiceForm.invoiceNo" required /></label><label>开票金额 <em>*</em><input v-model.number="invoiceForm.amount" type="number" min="0.01" :max="selectedPlan.planAmount-selectedPlan.invoicedAmount" step="0.01" required /></label><label>开票日期 <em>*</em><input v-model="invoiceForm.invoiceDate" type="date" :max="today" required /></label><label>发票类型 <em>*</em><select v-model="invoiceForm.invoiceType"><option value="VAT_SPECIAL">增值税专用发票</option><option value="VAT_NORMAL">增值税普通发票</option><option value="OTHER">其他</option></select></label><label>发票抬头 <em>*</em><input v-model.trim="invoiceForm.invoiceTitle" required /></label><div class="drawer-actions"><button type="button" class="secondary-button" @click="drawer=null">取消</button><button class="primary-button" :disabled="saving">确认登记发票</button></div></form>
   <div v-else-if="drawer==='risk'&&selectedRisk" class="risk-drawer-body"><div class="risk-fact"><strong>事实依据（不可修改）</strong><p>{{selectedRisk.factSummary}}</p></div><div class="risk-action-grid"><button :disabled="selectedRisk.riskStatus!=='NEW'||saving" @click="perform(()=>financeApi.acknowledge(selectedRisk!.id),'风险已确认知悉。')"><strong>确认风险</strong><small>表示已知悉，不代表风险解决</small></button><button :disabled="!['NEW','ACKNOWLEDGED','IN_PROGRESS'].includes(selectedRisk.riskStatus)" @click="riskActionMode='IN_PROGRESS'"><strong>进入处理中</strong><small>填写处理人和处理方案</small></button><button :disabled="selectedRisk.riskStatus!=='PENDING_CLOSE'||saving" @click="perform(()=>financeApi.closeRisk(selectedRisk!.id),'风险已结案。')"><strong>标记结案</strong><small>仅在根因消除后可用</small></button><button :disabled="selectedRisk.riskStatus==='CLOSED'" @click="riskActionMode='IGNORED'"><strong>忽略风险</strong><small>必须填写理由和复查日</small></button></div><form v-if="riskActionMode==='IN_PROGRESS'" @submit.prevent="perform(()=>financeApi.startRisk(selectedRisk!.id,Number(riskForm.handlerMembershipId),riskForm.handlingPlan),'风险已进入处理中。')"><label>处理人 <em>*</em><select v-model="riskForm.handlerMembershipId" required><option v-for="m in members" :key="m.membershipId" :value="m.membershipId">{{m.displayName}}</option></select></label><label>处理方案 <em>*</em><textarea v-model.trim="riskForm.handlingPlan" rows="4" required /></label><button class="primary-button" :disabled="saving">保存并进入处理中</button></form><form v-if="riskActionMode==='IGNORED'" @submit.prevent="perform(()=>financeApi.ignoreRisk(selectedRisk!.id,riskForm.reason,riskForm.reviewDate),'风险已忽略，复查日前不重复提醒。')"><label>忽略理由 <em>*</em><textarea v-model.trim="riskForm.reason" rows="3" required /></label><label>复查日 <em>*</em><input v-model="riskForm.reviewDate" type="date" :min="reviewDefault" required /></label><button class="primary-button" :disabled="saving">确认忽略</button></form></div>
  </aside></div>
 </AppShell>
</template>
