<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import AppShell from'@/components/AppShell.vue';import{organizationApi,type OrganizationMember}from'@/api/organization';import{contractApi,type ContractItem}from'@/api/contracts'
const members=ref<OrganizationMember[]>([]),contracts=ref<ContractItem[]>([]),loading=ref(true),saving=ref(false),error=ref(''),message=ref('');const createOpen=ref(false);const form=reactive({username:'',displayName:'',initialPassword:'',roleCodes:['MEMBER'] as string[]});const grant=reactive({contractId:0,membershipId:0});const roles=[['ENTERPRISE_ADMIN','企业管理员'],['CONTRACT_OWNER','合同负责人'],['FINANCE','财务'],['PROJECT_OWNER','项目负责人'],['LEGAL','法务'],['MEMBER','普通成员']]
async function load(){loading.value=true;error.value='';try{[members.value,contracts.value]=await Promise.all([organizationApi.members(),contractApi.list()])}catch(e){error.value=e instanceof Error?e.message:'组织数据加载失败'}finally{loading.value=false}}
async function perform(action:()=>Promise<unknown>,text:string){saving.value=true;error.value='';try{await action();message.value=text;await load()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{saving.value=false}}
function create(){perform(()=>organizationApi.create(form),'成员已创建。');createOpen.value=false}
function toggleRole(member:OrganizationMember,role:string){const next=member.roleCodes.includes(role)?member.roleCodes.filter(v=>v!==role):[...member.roleCodes,role];if(next.length)perform(()=>organizationApi.roles(member.membershipId,next),'角色已更新。')}
onMounted(load)
</script>
<template><AppShell title="组织与设置" subtitle="企业成员、预置角色与合同访问范围"><template #actions><button class="primary-button compact" @click="createOpen=true">＋ 添加成员</button></template><p v-if="error" class="feedback error">{{error}}</p><p v-if="message" class="feedback success">{{message}}</p><section class="panel-card"><div class="panel-heading"><div><h3>成员与角色</h3><p>角色权限由后端校验，停用前必须处理未完成任务</p></div></div><div v-if="loading" class="loading-state">正在读取成员…</div><div v-else class="table-scroll"><table class="contract-table"><thead><tr><th>成员</th><th>账号</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="m in members" :key="m.membershipId"><td><strong>{{m.displayName}}</strong></td><td>{{m.username}}</td><td><div class="role-checks"><label v-for="r in roles" :key="r[0]"><input type="checkbox" :checked="m.roleCodes.includes(r[0])" @change="toggleRole(m,r[0])">{{r[1]}}</label></div></td><td><span class="status-badge" :class="m.status==='ACTIVE'?'settled':'draft'">{{m.status==='ACTIVE'?'有效':'已停用'}}</span></td><td><button class="text-button" @click="perform(()=>organizationApi.status(m.membershipId,m.status==='ACTIVE'?'INACTIVE':'ACTIVE'),m.status==='ACTIVE'?'成员已停用。':'成员已启用。')">{{m.status==='ACTIVE'?'停用':'启用'}}</button></td></tr></tbody></table></div></section><section class="panel-card organization-grant"><div class="panel-heading"><div><h3>合同授权</h3><p>为非全局角色授予单份合同读取权限</p></div></div><div class="inline-form"><select v-model="grant.contractId"><option :value="0">选择合同</option><option v-for="c in contracts" :key="c.id" :value="c.id">{{c.contractNo}} {{c.name}}</option></select><select v-model="grant.membershipId"><option :value="0">选择成员</option><option v-for="m in members" :key="m.membershipId" :value="m.membershipId">{{m.displayName}}</option></select><button class="primary-button" :disabled="!grant.contractId||!grant.membershipId" @click="perform(()=>organizationApi.grant(grant.contractId,grant.membershipId),'合同权限已授予。')">授予读取权限</button><button class="secondary-button" :disabled="!grant.contractId||!grant.membershipId" @click="perform(()=>organizationApi.revoke(grant.contractId,grant.membershipId),'合同权限已撤销。')">撤销</button></div></section><div v-if="createOpen" class="drawer-backdrop" @click.self="createOpen=false"><aside class="upload-drawer"><div class="drawer-heading"><div><h2>添加企业成员</h2><p>创建本地演示账号并分配预置角色</p></div><button class="icon-button" @click="createOpen=false">×</button></div><form @submit.prevent="create"><label>账号<input v-model="form.username" required></label><label>姓名<input v-model="form.displayName" required></label><label>初始密码<input v-model="form.initialPassword" type="password" minlength="8" required></label><fieldset><legend>角色</legend><label v-for="r in roles" :key="r[0]"><input v-model="form.roleCodes" type="checkbox" :value="r[0]">{{r[1]}}</label></fieldset><button class="primary-button full-button" :disabled="saving">创建成员</button></form></aside></div></AppShell></template>
