package com.contractguard.platform.risk;
import com.contractguard.platform.audit.AuditService; import com.contractguard.platform.common.ApiException; import com.contractguard.platform.identity.MembershipMapper; import com.contractguard.platform.receivable.*; import com.contractguard.platform.security.AuthPrincipal;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.List;
@Service
public class RiskService { private final RiskMapper mapper;private final RiskEvaluationService evaluator;private final ReceivableMapper receivables;private final MembershipMapper memberships;private final AuditService audit; public RiskService(RiskMapper m,RiskEvaluationService e,ReceivableMapper r,MembershipMapper mm,AuditService a){mapper=m;evaluator=e;receivables=r;memberships=mm;audit=a;}
 public List<RiskResponse> list(AuthPrincipal p){read(p);evaluator.scan(p.tenantId());return mapper.findAll(p.tenantId()).stream().map(RiskResponse::from).toList();}
 public List<RiskResponse> listByContract(AuthPrincipal p,Long contractId){return list(p).stream().filter(r->r.contractId().equals(contractId)).toList();}
 @Transactional public RiskResponse acknowledge(AuthPrincipal p,Long id){write(p,null);if(mapper.acknowledge(p.tenantId(),id)==0)throw conflict("RISK_NOT_ACKNOWLEDGEABLE","当前风险状态不能确认");record(p,"RISK_ACKNOWLEDGED",id);return response(p,id);}
 @Transactional public RiskResponse start(AuthPrincipal p,Long id,StartRiskRequest r){RiskRow risk=require(p,id);write(p,risk);if(!memberships.existsActive(p.tenantId(),r.handlerMembershipId()))throw bad("RISK_HANDLER_INVALID","处理人必须是本企业有效成员");if(mapper.start(p.tenantId(),id,r.handlerMembershipId(),r.handlingPlan().trim())==0)throw conflict("RISK_NOT_ACTIONABLE","当前风险状态不能进入处理中");record(p,"RISK_IN_PROGRESS",id);return response(p,id);}
 @Transactional public RiskResponse ignore(AuthPrincipal p,Long id,IgnoreRiskRequest r){RiskRow risk=require(p,id);write(p,risk);if(!r.reviewDate().isAfter(LocalDate.now()))throw bad("RISK_REVIEW_DATE_INVALID","复查日必须晚于今天");if(mapper.ignore(p.tenantId(),id,r.reason().trim(),r.reviewDate())==0)throw conflict("RISK_NOT_IGNORABLE","当前风险状态不能忽略");record(p,"RISK_IGNORED",id);return response(p,id);}
 @Transactional public RiskResponse close(AuthPrincipal p,Long id){RiskRow risk=require(p,id);write(p,risk);if("RECEIVABLE_OVERDUE".equals(risk.getRuleCode())){ReceivableRow plan=receivables.findById(p.tenantId(),risk.getObjectId());if(plan!=null&&"OVERDUE".equals(ReceivableResponse.from(plan,LocalDate.now()).dueStatus()))throw conflict("RISK_ROOT_CAUSE_REMAINS","应收仍逾期且存在余额，不能结案");}if(mapper.close(p.tenantId(),id)==0)throw conflict("RISK_NOT_CLOSABLE","风险尚未进入待结案状态");record(p,"RISK_CLOSED",id);return response(p,id);}
 private RiskResponse response(AuthPrincipal p,Long id){return RiskResponse.from(require(p,id));} private RiskRow require(AuthPrincipal p,Long id){read(p);RiskRow r=mapper.findById(p.tenantId(),id);if(r==null)throw new ApiException(HttpStatus.NOT_FOUND,"RISK_NOT_FOUND","未找到风险");return r;}
 private void read(AuthPrincipal p){workspace(p);if(p.roleCodes().stream().noneMatch(r->List.of("ENTERPRISE_ADMIN","CONTRACT_OWNER","FINANCE","LEGAL").contains(r)))throw new ApiException(HttpStatus.FORBIDDEN,"RISK_READ_FORBIDDEN","当前角色无权查看风险");}
 private void write(AuthPrincipal p,RiskRow risk){workspace(p);boolean allowed=p.roleCodes().stream().anyMatch(r->List.of("ENTERPRISE_ADMIN","CONTRACT_OWNER","LEGAL").contains(r))||(risk!=null&&"RECEIVABLE_OVERDUE".equals(risk.getRuleCode())&&p.roleCodes().contains("FINANCE"));if(!allowed)throw new ApiException(HttpStatus.FORBIDDEN,"RISK_WRITE_FORBIDDEN","当前角色无权处置该风险");}
 private void workspace(AuthPrincipal p){if(!p.hasWorkspace())throw new ApiException(HttpStatus.FORBIDDEN,"WORKSPACE_REQUIRED","请先选择企业工作空间");} private void record(AuthPrincipal p,String action,Long id){audit.record(p.tenantId(),p.userId(),p.membershipId(),action,"RISK",id.toString());} private ApiException bad(String c,String m){return new ApiException(HttpStatus.BAD_REQUEST,c,m);}private ApiException conflict(String c,String m){return new ApiException(HttpStatus.CONFLICT,c,m);}
}

