CREATE TABLE contract_parse_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    contract_version_id BIGINT NOT NULL,
    job_status VARCHAR(32) NOT NULL,
    execution_mode VARCHAR(32) NOT NULL,
    failure_message VARCHAR(500) NULL,
    created_by_membership_id BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    KEY idx_parse_jobs_contract (tenant_id, contract_id, created_at),
    CONSTRAINT fk_parse_jobs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_parse_jobs_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_parse_jobs_version FOREIGN KEY (contract_version_id) REFERENCES contract_versions(id),
    CONSTRAINT fk_parse_jobs_creator FOREIGN KEY (created_by_membership_id) REFERENCES memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE contract_clauses (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    contract_version_id BIGINT NOT NULL,
    parse_job_id BIGINT NULL,
    clause_type VARCHAR(32) NOT NULL,
    clause_title VARCHAR(255) NOT NULL,
    clause_content TEXT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_page_no INT NULL,
    source_excerpt VARCHAR(1000) NULL,
    confidence DECIMAL(5,2) NULL,
    confirmation_status VARCHAR(32) NOT NULL,
    confirmed_by_membership_id BIGINT NULL,
    confirmed_at DATETIME(3) NULL,
    created_by_membership_id BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    KEY idx_contract_clauses_contract (tenant_id, contract_id, clause_type),
    CONSTRAINT fk_clauses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_clauses_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_clauses_version FOREIGN KEY (contract_version_id) REFERENCES contract_versions(id),
    CONSTRAINT fk_clauses_job FOREIGN KEY (parse_job_id) REFERENCES contract_parse_jobs(id),
    CONSTRAINT fk_clauses_creator FOREIGN KEY (created_by_membership_id) REFERENCES memberships(id),
    CONSTRAINT fk_clauses_confirmer FOREIGN KEY (confirmed_by_membership_id) REFERENCES memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
