CREATE TABLE receivable_plans (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    source_clause_id BIGINT NULL,
    plan_name VARCHAR(255) NOT NULL,
    plan_amount DECIMAL(18,2) NOT NULL,
    trigger_status VARCHAR(32) NOT NULL,
    due_date DATE NULL,
    created_by_membership_id BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    KEY idx_receivable_due (tenant_id, trigger_status, due_date),
    KEY idx_receivable_contract (tenant_id, contract_id),
    CONSTRAINT fk_receivable_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_receivable_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_receivable_clause FOREIGN KEY (source_clause_id) REFERENCES contract_clauses(id),
    CONSTRAINT fk_receivable_creator FOREIGN KEY (created_by_membership_id) REFERENCES memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE receipt_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    receivable_plan_id BIGINT NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    receipt_date DATE NOT NULL,
    payment_method VARCHAR(32) NOT NULL,
    payer_name VARCHAR(255) NOT NULL,
    reference_no VARCHAR(128) NULL,
    note VARCHAR(1000) NULL,
    record_status VARCHAR(16) NOT NULL,
    request_key VARCHAR(64) NOT NULL,
    created_by_membership_id BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_receipt_request (tenant_id, request_key),
    UNIQUE KEY uk_receipt_reference (tenant_id, reference_no),
    KEY idx_receipt_plan (tenant_id, receivable_plan_id, record_status),
    CONSTRAINT fk_receipt_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_receipt_plan FOREIGN KEY (receivable_plan_id) REFERENCES receivable_plans(id),
    CONSTRAINT fk_receipt_creator FOREIGN KEY (created_by_membership_id) REFERENCES memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE invoice_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    receivable_plan_id BIGINT NOT NULL,
    invoice_no VARCHAR(128) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    invoice_date DATE NOT NULL,
    invoice_type VARCHAR(64) NOT NULL,
    invoice_title VARCHAR(255) NOT NULL,
    record_status VARCHAR(16) NOT NULL,
    request_key VARCHAR(64) NOT NULL,
    created_by_membership_id BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_invoice_request (tenant_id, request_key),
    UNIQUE KEY uk_invoice_no (tenant_id, invoice_no),
    KEY idx_invoice_plan (tenant_id, receivable_plan_id, record_status),
    CONSTRAINT fk_invoice_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_invoice_plan FOREIGN KEY (receivable_plan_id) REFERENCES receivable_plans(id),
    CONSTRAINT fk_invoice_creator FOREIGN KEY (created_by_membership_id) REFERENCES memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE risk_cases (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    rule_code VARCHAR(64) NOT NULL,
    object_type VARCHAR(32) NOT NULL,
    object_id BIGINT NOT NULL,
    dedup_key VARCHAR(160) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    risk_status VARCHAR(32) NOT NULL,
    fact_summary VARCHAR(1000) NOT NULL,
    handler_membership_id BIGINT NULL,
    handling_plan VARCHAR(1000) NULL,
    review_date DATE NULL,
    ignored_reason VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_risk_dedup (tenant_id, dedup_key),
    KEY idx_risk_status (tenant_id, risk_status, severity),
    CONSTRAINT fk_risk_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_risk_contract FOREIGN KEY (contract_id) REFERENCES contracts(id),
    CONSTRAINT fk_risk_handler FOREIGN KEY (handler_membership_id) REFERENCES memberships(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
