package com.contractguard.platform.receivable;

import com.contractguard.platform.audit.AuditService; import com.contractguard.platform.common.ApiException;
import com.contractguard.platform.contract.ContractMapper; import com.contractguard.platform.contract.ContractRow;
import com.contractguard.platform.risk.RiskEvaluationService; import com.contractguard.platform.security.AuthPrincipal;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.LocalDate; import java.util.List;

@Service
public class ReceivableService {
    private final ReceivableMapper mapper; private final ContractMapper contractMapper; private final AuditService audit; private final RiskEvaluationService risks;
    public ReceivableService(ReceivableMapper mapper,ContractMapper contractMapper,AuditService audit,RiskEvaluationService risks){this.mapper=mapper;this.contractMapper=contractMapper;this.audit=audit;this.risks=risks;}
    public List<ReceivableResponse> list(AuthPrincipal p){requireRead(p); return mapper.findAll(p.tenantId()).stream().map(r->ReceivableResponse.from(r,LocalDate.now())).toList();}
    public List<ReceivableResponse> listByContract(AuthPrincipal p,Long contractId){return list(p).stream().filter(r->r.contractId().equals(contractId)).toList();}
    @Transactional public ReceivableResponse createPlan(AuthPrincipal p,CreateReceivableRequest request){requirePlanWrite(p); if(!List.of("TRIGGERED","PENDING_TRIGGER").contains(request.triggerStatus())) throw bad("RECEIVABLE_TRIGGER_INVALID","触发状态不正确"); if("TRIGGERED".equals(request.triggerStatus())&&request.dueDate()==null) throw bad("RECEIVABLE_DUE_DATE_REQUIRED","已触发应收必须填写到期日"); if("PENDING_TRIGGER".equals(request.triggerStatus())&&request.dueDate()!=null) throw bad("RECEIVABLE_DUE_DATE_NOT_ALLOWED","待触发应收不能填写虚构到期日"); ContractRow c=contractMapper.findDetail(request.contractId(),p.tenantId()); if(c==null) throw bad("CONTRACT_NOT_FOUND","合同不存在或不属于当前企业"); ReceivableRow row=new ReceivableRow(); mapper.insertPlan(row,p.tenantId(),p.membershipId(),request); audit.record(p.tenantId(),p.userId(),p.membershipId(),"RECEIVABLE_PLAN_CREATED","RECEIVABLE_PLAN",row.getId().toString()); ReceivableRow saved=mapper.findById(p.tenantId(),row.getId()); risks.evaluate(p.tenantId(),saved); return ReceivableResponse.from(saved,LocalDate.now());}
    @Transactional public ReceivableResponse addReceipt(AuthPrincipal p,Long id,CreateReceiptRequest request){requireFinanceWrite(p); if(request.receiptDate().isAfter(LocalDate.now())) throw bad("RECEIPT_DATE_FUTURE","实际到账日期不能晚于今天"); ReceivableRow row=lock(p,id); if(mapper.receiptRequestExists(p.tenantId(),request.requestKey())) return ReceivableResponse.from(row,LocalDate.now()); String ref=normalize(request.referenceNo()); if(ref!=null&&mapper.receiptReferenceExists(p.tenantId(),ref)) throw new ApiException(HttpStatus.CONFLICT,"RECEIPT_REFERENCE_EXISTS","参考流水号已存在，请先核对是否重复登记"); BigDecimal balance=row.getPlanAmount().subtract(value(mapper.sumReceipts(p.tenantId(),id))); if(request.amount().compareTo(balance)>0) throw bad("RECEIPT_AMOUNT_EXCEEDS_BALANCE","本次回款金额不能超过当前余额"); mapper.insertReceipt(p.tenantId(),id,p.membershipId(),new CreateReceiptRequest(request.amount(),request.receiptDate(),request.paymentMethod().trim(),request.payerName().trim(),ref,normalize(request.note()),request.requestKey())); audit.record(p.tenantId(),p.userId(),p.membershipId(),"RECEIPT_RECORDED","RECEIVABLE_PLAN",id.toString()); ReceivableRow saved=mapper.findById(p.tenantId(),id); risks.evaluate(p.tenantId(),saved); return ReceivableResponse.from(saved,LocalDate.now());}
    @Transactional public ReceivableResponse addInvoice(AuthPrincipal p,Long id,CreateInvoiceRequest request){requireFinanceWrite(p); if(request.invoiceDate().isAfter(LocalDate.now())) throw bad("INVOICE_DATE_FUTURE","开票日期不能晚于今天"); ReceivableRow row=lock(p,id); if(mapper.invoiceRequestExists(p.tenantId(),request.requestKey())) return ReceivableResponse.from(row,LocalDate.now()); if(mapper.invoiceNoExists(p.tenantId(),request.invoiceNo().trim())) throw new ApiException(HttpStatus.CONFLICT,"INVOICE_NO_EXISTS","该发票编号在本企业已登记"); BigDecimal remaining=row.getPlanAmount().subtract(value(mapper.sumInvoices(p.tenantId(),id))); if(request.amount().compareTo(remaining)>0) throw bad("INVOICE_AMOUNT_EXCEEDS_PLAN","累计开票金额不能超过应收计划金额"); mapper.insertInvoice(p.tenantId(),id,p.membershipId(),new CreateInvoiceRequest(request.invoiceNo().trim(),request.amount(),request.invoiceDate(),request.invoiceType().trim(),request.invoiceTitle().trim(),request.requestKey())); audit.record(p.tenantId(),p.userId(),p.membershipId(),"INVOICE_RECORDED","RECEIVABLE_PLAN",id.toString()); return ReceivableResponse.from(mapper.findById(p.tenantId(),id),LocalDate.now());}
    private ReceivableRow lock(AuthPrincipal p,Long id){ReceivableRow r=mapper.findByIdForUpdate(p.tenantId(),id);if(r==null)throw new ApiException(HttpStatus.NOT_FOUND,"RECEIVABLE_NOT_FOUND","未找到应收计划");return r;}
    private void requireRead(AuthPrincipal p){workspace(p);if(p.roleCodes().stream().noneMatch(r->List.of("ENTERPRISE_ADMIN","CONTRACT_OWNER","FINANCE").contains(r)))throw new ApiException(HttpStatus.FORBIDDEN,"FINANCE_READ_FORBIDDEN","当前角色无权查看财务数据");}
    private void requirePlanWrite(AuthPrincipal p){workspace(p);if(p.roleCodes().stream().noneMatch(r->List.of("ENTERPRISE_ADMIN","CONTRACT_OWNER","FINANCE").contains(r)))throw new ApiException(HttpStatus.FORBIDDEN,"RECEIVABLE_WRITE_FORBIDDEN","当前角色无权创建应收计划");}
    private void requireFinanceWrite(AuthPrincipal p){workspace(p);if(p.roleCodes().stream().noneMatch(r->List.of("ENTERPRISE_ADMIN","FINANCE").contains(r)))throw new ApiException(HttpStatus.FORBIDDEN,"FINANCE_WRITE_FORBIDDEN","仅企业管理员或财务人员可登记回款和发票");}
    private void workspace(AuthPrincipal p){if(!p.hasWorkspace())throw new ApiException(HttpStatus.FORBIDDEN,"WORKSPACE_REQUIRED","请先选择企业工作空间");}
    private ApiException bad(String c,String m){return new ApiException(HttpStatus.BAD_REQUEST,c,m);} private BigDecimal value(BigDecimal v){return v==null?BigDecimal.ZERO:v;} private String normalize(String v){return v==null||v.isBlank()?null:v.trim();}
}

