package com.contractguard.platform.organization;
import com.contractguard.platform.audit.AuditService; import com.contractguard.platform.common.ApiException; import com.contractguard.platform.identity.RoleCode; import com.contractguard.platform.security.AuthPrincipal; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class OrganizationService { private final OrganizationMapper mapper; private final PasswordEncoder encoder; private final AuditService audit; public OrganizationService(OrganizationMapper mapper,PasswordEncoder encoder,AuditService audit){this.mapper=mapper;this.encoder=encoder;this.audit=audit;}
 public List<OrganizationMemberResponse> members(AuthPrincipal p){admin(p);return mapper.members(p.tenantId()).stream().map(OrganizationMemberResponse::from).toList();}
 @Transactional public List<OrganizationMemberResponse> create(AuthPrincipal p,CreateMemberRequest r){admin(p);if(mapper.usernameExists(r.username().trim())>0)throw conflict("USERNAME_EXISTS","账号名已存在");OrganizationMemberRow row=new OrganizationMemberRow();row.setUsername(r.username().trim());row.setDisplayName(r.displayName().trim());mapper.insertUser(row,encoder.encode(r.initialPassword()));mapper.insertMembership(p.tenantId(),row);for(String role:roles(r.roleCodes()))mapper.insertRole(row.getMembershipId(),role);audit.record(p.tenantId(),p.userId(),p.membershipId(),"MEMBER_CREATED","MEMBERSHIP",row.getMembershipId().toString());return members(p);}
 @Transactional public List<OrganizationMemberResponse> roles(AuthPrincipal p,Long id,UpdateRolesRequest r){admin(p);if(!mapper.exists(p.tenantId(),id))throw conflict("MEMBER_NOT_FOUND","成员不存在");Set<String> roles=roles(r.roleCodes());if(p.membershipId().equals(id)&&!roles.contains("ENTERPRISE_ADMIN"))throw conflict("SELF_ADMIN_ROLE_REQUIRED","不能移除自己的企业管理员角色");mapper.deleteRoles(p.tenantId(),id);for(String role:roles)mapper.insertRole(id,role);audit.record(p.tenantId(),p.userId(),p.membershipId(),"MEMBER_ROLES_UPDATED","MEMBERSHIP",id.toString());return members(p);}
 @Transactional public List<OrganizationMemberResponse> status(AuthPrincipal p,Long id,String status){admin(p);if(p.membershipId().equals(id)&&"INACTIVE".equals(status))throw conflict("SELF_DEACTIVATE_FORBIDDEN","不能停用当前登录成员");if(!Set.of("ACTIVE","INACTIVE").contains(status))throw new ApiException(HttpStatus.BAD_REQUEST,"MEMBER_STATUS_INVALID","成员状态无效");if("INACTIVE".equals(status)&&mapper.unfinishedTasks(p.tenantId(),id)>0)throw conflict("MEMBER_HAS_UNFINISHED_TASKS","成员仍有未完成任务，请先转交");if(mapper.updateStatus(p.tenantId(),id,status)==0)throw conflict("MEMBER_NOT_FOUND","成员不存在");audit.record(p.tenantId(),p.userId(),p.membershipId(),"MEMBER_STATUS_UPDATED","MEMBERSHIP",id.toString());return members(p);}
 @Transactional public void grant(AuthPrincipal p,ContractGrantRequest r){admin(p);if(!mapper.exists(p.tenantId(),r.membershipId())||mapper.contractExists(p.tenantId(),r.contractId())==0)throw conflict("GRANT_SCOPE_INVALID","合同或成员不属于当前企业");mapper.grant(p.tenantId(),r.contractId(),r.membershipId());audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_ACCESS_GRANTED","CONTRACT",r.contractId().toString());}
 @Transactional public void revoke(AuthPrincipal p,ContractGrantRequest r){admin(p);mapper.revoke(p.tenantId(),r.contractId(),r.membershipId());audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_ACCESS_REVOKED","CONTRACT",r.contractId().toString());}
 private Set<String> roles(List<String> values){Set<String> result=new LinkedHashSet<>();for(String value:values)try{result.add(RoleCode.valueOf(value).name());}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"ROLE_INVALID","存在无效角色");}result.remove("PLATFORM_OPERATOR");if(result.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"ROLE_REQUIRED","至少选择一个企业角色");return result;}
 private void admin(AuthPrincipal p){if(!p.hasWorkspace()||!p.roleCodes().contains("ENTERPRISE_ADMIN"))throw new ApiException(HttpStatus.FORBIDDEN,"ORGANIZATION_FORBIDDEN","仅企业管理员可管理组织与权限");} private ApiException conflict(String c,String m){return new ApiException(HttpStatus.CONFLICT,c,m);}}

