package com.contractguard.platform.contract;
import org.apache.ibatis.annotations.*; import java.math.BigDecimal; import java.util.List;
@Mapper public interface ContractLifecycleMapper {
 @Select("SELECT v.id,v.contract_id,v.version_no,v.version_status,f.original_filename,r.id change_request_id,r.requester_membership_id,r.reviewer_membership_id,r.change_summary,r.request_status,r.review_note,v.created_at,r.reviewed_at FROM contract_versions v JOIN file_objects f ON f.id=v.source_file_id LEFT JOIN contract_version_change_requests r ON r.candidate_version_id=v.id AND r.tenant_id=v.tenant_id WHERE v.tenant_id=#{tenantId} AND v.contract_id=#{contractId} ORDER BY v.version_no DESC") List<ContractVersionRow> versions(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Select("SELECT COALESCE(MAX(version_no),0)+1 FROM contract_versions WHERE tenant_id=#{tenantId} AND contract_id=#{contractId}") int nextVersion(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Insert("INSERT INTO contract_versions(tenant_id,contract_id,source_file_id,version_no,version_status,created_by_membership_id) VALUES(#{tenantId},#{contractId},#{fileId},#{versionNo},'CANDIDATE',#{membershipId})") @Options(useGeneratedKeys=true,keyProperty="row.id",keyColumn="id") void insertVersion(@Param("row")ContractVersionRow row,@Param("tenantId")Long tenantId,@Param("contractId")Long contractId,@Param("fileId")Long fileId,@Param("versionNo")int versionNo,@Param("membershipId")Long membershipId);
 @Insert("INSERT INTO contract_version_change_requests(tenant_id,contract_id,candidate_version_id,requester_membership_id,reviewer_membership_id,change_summary,request_status) VALUES(#{tenantId},#{contractId},#{versionId},#{requesterId},#{reviewerId},#{summary},'PENDING')") @Options(useGeneratedKeys=true,keyProperty="row.changeRequestId",keyColumn="id") void insertRequest(@Param("row")ContractVersionRow row,@Param("tenantId")Long tenantId,@Param("contractId")Long contractId,@Param("versionId")Long versionId,@Param("requesterId")Long requesterId,@Param("reviewerId")Long reviewerId,@Param("summary")String summary);
 @Select("SELECT v.id,v.contract_id,v.version_no,v.version_status,r.id change_request_id,r.requester_membership_id,r.reviewer_membership_id,r.change_summary,r.request_status FROM contract_version_change_requests r JOIN contract_versions v ON v.id=r.candidate_version_id AND v.tenant_id=r.tenant_id WHERE r.tenant_id=#{tenantId} AND r.id=#{requestId} AND r.reviewer_membership_id=#{reviewerId} FOR UPDATE") ContractVersionRow lockRequest(@Param("tenantId")Long tenantId,@Param("requestId")Long requestId,@Param("reviewerId")Long reviewerId);
 @Update("UPDATE contract_version_change_requests SET request_status=#{status},review_note=#{note},reviewed_at=NOW(3) WHERE tenant_id=#{tenantId} AND id=#{requestId} AND request_status='PENDING'") int reviewRequest(@Param("tenantId")Long tenantId,@Param("requestId")Long requestId,@Param("status")String status,@Param("note")String note);
 @Update("UPDATE contract_versions v JOIN contracts c ON c.current_version_id=v.id AND c.tenant_id=v.tenant_id SET v.version_status='SUPERSEDED' WHERE v.tenant_id=#{tenantId} AND c.id=#{contractId}") void supersede(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Update("UPDATE contract_versions SET version_status=#{status} WHERE tenant_id=#{tenantId} AND id=#{versionId}") void versionStatus(@Param("tenantId")Long tenantId,@Param("versionId")Long versionId,@Param("status")String status);
 @Update("UPDATE contracts SET current_version_id=#{versionId},business_status='TERMS_REVIEW' WHERE tenant_id=#{tenantId} AND id=#{contractId}") void activateVersion(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId,@Param("versionId")Long versionId);
 @Select("SELECT COUNT(*) FROM fulfillment_tasks WHERE tenant_id=#{tenantId} AND contract_id=#{contractId} AND task_status NOT IN ('COMPLETED','CANCELLED')") long unfinishedTasks(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Select("SELECT COUNT(*) FROM evidence_submissions e JOIN fulfillment_tasks t ON t.id=e.task_id WHERE e.tenant_id=#{tenantId} AND t.contract_id=#{contractId} AND e.review_status='PENDING_REVIEW'") long pendingReviews(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Select("SELECT COUNT(*) FROM risk_cases WHERE tenant_id=#{tenantId} AND contract_id=#{contractId} AND risk_status NOT IN ('CLOSED','IGNORED')") long activeRisks(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Select("SELECT COALESCE(SUM(p.plan_amount-(SELECT COALESCE(SUM(r.amount),0) FROM receipt_records r WHERE r.tenant_id=p.tenant_id AND r.receivable_plan_id=p.id AND r.record_status='ACTIVE')),0) FROM receivable_plans p WHERE p.tenant_id=#{tenantId} AND p.contract_id=#{contractId}") BigDecimal balance(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId);
 @Update("UPDATE contracts SET business_status=#{status},termination_reason=#{reason} WHERE tenant_id=#{tenantId} AND id=#{contractId} AND archive_status='UNARCHIVED'") int lifecycle(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId,@Param("status")String status,@Param("reason")String reason);
 @Insert("INSERT INTO contract_archive_snapshots(tenant_id,contract_id,contract_version_id,snapshot_json,archived_by_membership_id,archive_reason) VALUES(#{tenantId},#{contractId},#{versionId},CAST(#{snapshot} AS JSON),#{membershipId},#{reason})") void archiveSnapshot(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId,@Param("versionId")Long versionId,@Param("snapshot")String snapshot,@Param("membershipId")Long membershipId,@Param("reason")String reason);
 @Update("UPDATE contracts SET archive_status=#{status} WHERE tenant_id=#{tenantId} AND id=#{contractId}") int archiveStatus(@Param("tenantId")Long tenantId,@Param("contractId")Long contractId,@Param("status")String status);
}

