package com.contractguard.platform.contract;

import com.contractguard.platform.audit.AuditService;
import com.contractguard.platform.common.ApiException;
import com.contractguard.platform.identity.MembershipMapper;
import com.contractguard.platform.security.AuthPrincipal;
import com.contractguard.platform.storage.PrivateFileStorage;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.math.BigDecimal;
import java.util.*;

@Service
public class ContractLifecycleService {
    private static final long MAX=20L*1024*1024;
    private final ContractLifecycleMapper lifecycle;private final ContractMapper contracts;private final MembershipMapper memberships;private final PrivateFileStorage storage;private final AuditService audit;private final ObjectMapper json;
    public ContractLifecycleService(ContractLifecycleMapper lifecycle,ContractMapper contracts,MembershipMapper memberships,PrivateFileStorage storage,AuditService audit,ObjectMapper json){this.lifecycle=lifecycle;this.contracts=contracts;this.memberships=memberships;this.storage=storage;this.audit=audit;this.json=json;}
    public List<ContractVersionRow> versions(AuthPrincipal p,Long contractId){requireReadable(p,contractId);return lifecycle.versions(p.tenantId(),contractId);}
    @Transactional
    public List<ContractVersionRow> uploadVersion(AuthPrincipal p,Long contractId,MultipartFile file,String summary,Long reviewerId){ContractRow c=requireWritable(p,contractId);if("ARCHIVED".equals(c.getArchiveStatus()))throw conflict("CONTRACT_ARCHIVED","已归档合同不能上传新版本");validate(file,summary);if(p.membershipId().equals(reviewerId)||!memberships.existsActive(p.tenantId(),reviewerId))throw new ApiException(HttpStatus.BAD_REQUEST,"VERSION_REVIEWER_INVALID","审核人必须是同企业的其他有效成员");List<String> reviewerRoles=memberships.findRoleCodes(reviewerId);if(reviewerRoles.stream().noneMatch(r->r.equals("ENTERPRISE_ADMIN")||r.equals("LEGAL")))throw new ApiException(HttpStatus.BAD_REQUEST,"VERSION_REVIEWER_ROLE_INVALID","版本审核人必须是企业管理员或法务");String key=null;try{key=storage.store(p.tenantId(),file);FileObjectRow stored=new FileObjectRow();String filename=file.getOriginalFilename()==null?"contract":file.getOriginalFilename();String type=filename.toLowerCase(Locale.ROOT).endsWith(".pdf")?"application/pdf":"application/vnd.openxmlformats-officedocument.wordprocessingml.document";contracts.insertFile(stored,p.tenantId(),p.membershipId(),key,safe(filename),type,file.getSize());ContractVersionRow version=new ContractVersionRow();lifecycle.insertVersion(version,p.tenantId(),contractId,stored.getId(),lifecycle.nextVersion(p.tenantId(),contractId),p.membershipId());lifecycle.insertRequest(version,p.tenantId(),contractId,version.getId(),p.membershipId(),reviewerId,summary.trim());audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_VERSION_SUBMITTED","CONTRACT_VERSION",version.getId().toString());return versions(p,contractId);}catch(Exception e){if(key!=null)try{storage.delete(key);}catch(Exception ignored){}if(e instanceof RuntimeException re)throw re;throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"VERSION_FILE_STORE_FAILED","版本文件保存失败");}}
    @Transactional
    public List<ContractVersionRow> reviewVersion(AuthPrincipal p,Long contractId,Long requestId,ReviewVersionRequest request){requireReadable(p,contractId);if(p.roleCodes().stream().noneMatch(r->r.equals("ENTERPRISE_ADMIN")||r.equals("LEGAL")))throw new ApiException(HttpStatus.FORBIDDEN,"VERSION_REVIEW_ROLE_REQUIRED","只有企业管理员或法务可以审核版本变更");ContractVersionRow row=lifecycle.lockRequest(p.tenantId(),requestId,p.membershipId());if(row==null||!row.getContractId().equals(contractId)||!"PENDING".equals(row.getRequestStatus()))throw conflict("VERSION_REQUEST_NOT_REVIEWABLE","版本变更申请不存在或已处理");if(!request.approved()&&(request.note()==null||request.note().isBlank()))throw new ApiException(HttpStatus.BAD_REQUEST,"REVIEW_NOTE_REQUIRED","驳回必须填写原因");String status=request.approved()?"APPROVED":"REJECTED";lifecycle.reviewRequest(p.tenantId(),requestId,status,request.note());if(request.approved()){lifecycle.supersede(p.tenantId(),contractId);lifecycle.versionStatus(p.tenantId(),row.getId(),"ACTIVE");lifecycle.activateVersion(p.tenantId(),contractId,row.getId());}else lifecycle.versionStatus(p.tenantId(),row.getId(),"REJECTED");audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_VERSION_"+status,"CONTRACT_VERSION",row.getId().toString());return versions(p,contractId);}
    public ContractCompletionCheck check(AuthPrincipal p,Long id){requireReadable(p,id);long tasks=lifecycle.unfinishedTasks(p.tenantId(),id),reviews=lifecycle.pendingReviews(p.tenantId(),id),risks=lifecycle.activeRisks(p.tenantId(),id);BigDecimal actual=lifecycle.balance(p.tenantId(),id);boolean canSeeFinance=p.roleCodes().stream().anyMatch(r->r.equals("ENTERPRISE_ADMIN")||r.equals("FINANCE"));boolean canComplete=p.roleCodes().stream().anyMatch(r->r.equals("ENTERPRISE_ADMIN")||r.equals("CONTRACT_OWNER"));return new ContractCompletionCheck(tasks,reviews,risks,canSeeFinance?actual:null,canComplete&&tasks==0&&reviews==0&&risks==0&&actual.signum()==0);}
    @Transactional public ContractDetailResponse complete(AuthPrincipal p,Long id){requireWritable(p,id);long tasks=lifecycle.unfinishedTasks(p.tenantId(),id),reviews=lifecycle.pendingReviews(p.tenantId(),id),risks=lifecycle.activeRisks(p.tenantId(),id);BigDecimal balance=lifecycle.balance(p.tenantId(),id);if(tasks>0||reviews>0||risks>0||balance.signum()!=0)throw conflict("CONTRACT_COMPLETION_BLOCKED","仍有未完成任务、待审核、活动风险或未清应收");if(lifecycle.lifecycle(p.tenantId(),id,"COMPLETED",null)==0)throw conflict("CONTRACT_ARCHIVED","已归档合同不能变更状态");audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_COMPLETED","CONTRACT",id.toString());return detail(p,id);}
    @Transactional public ContractDetailResponse terminate(AuthPrincipal p,Long id,String reason){requireWritable(p,id);if(reason==null||reason.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"TERMINATION_REASON_REQUIRED","终止原因不能为空");if(lifecycle.lifecycle(p.tenantId(),id,"TERMINATED",reason.trim())==0)throw conflict("CONTRACT_ARCHIVED","已归档合同不能变更状态");audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_TERMINATED","CONTRACT",id.toString());return detail(p,id);}
    @Transactional public ContractDetailResponse archive(AuthPrincipal p,Long id,String reason){ContractRow c=requireAdmin(p,id);if(!List.of("COMPLETED","TERMINATED").contains(c.getBusinessStatus()))throw conflict("CONTRACT_NOT_ARCHIVABLE","只有已完成或已终止合同可以归档");if(reason==null||reason.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"ARCHIVE_REASON_REQUIRED","归档原因不能为空");try{Map<String,Object> snapshot=new LinkedHashMap<>();snapshot.put("contract",Map.of("id",c.getId(),"contractNo",c.getContractNo(),"status",c.getBusinessStatus(),"versionId",c.getCurrentVersionId()));snapshot.put("completion",check(p,id));snapshot.put("versions",versions(p,id));lifecycle.archiveSnapshot(p.tenantId(),id,c.getCurrentVersionId(),json.writeValueAsString(snapshot),p.membershipId(),reason.trim());lifecycle.archiveStatus(p.tenantId(),id,"ARCHIVED");audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_ARCHIVED","CONTRACT",id.toString());return detail(p,id);}catch(Exception e){if(e instanceof RuntimeException re)throw re;throw new IllegalStateException(e);}}
    @Transactional public ContractDetailResponse unarchive(AuthPrincipal p,Long id,String reason){requireAdmin(p,id);if(reason==null||reason.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"UNARCHIVE_REASON_REQUIRED","解档原因不能为空");lifecycle.archiveStatus(p.tenantId(),id,"UNARCHIVED");audit.record(p.tenantId(),p.userId(),p.membershipId(),"CONTRACT_UNARCHIVED","CONTRACT",id.toString());return detail(p,id);}
    private ContractDetailResponse detail(AuthPrincipal p,Long id){ContractRow c=contracts.findDetail(id,p.tenantId());return ContractDetailResponse.of(c,contracts.findLatestParseJob(p.tenantId(),id),contracts.findClauses(p.tenantId(),id));}
    private ContractRow requireAdmin(AuthPrincipal p,Long id){if(!p.roleCodes().contains("ENTERPRISE_ADMIN"))throw new ApiException(HttpStatus.FORBIDDEN,"CONTRACT_ADMIN_REQUIRED","仅企业管理员可执行归档操作");return requireReadable(p,id);}
    private ContractRow requireWritable(AuthPrincipal p,Long id){if(p.roleCodes().stream().noneMatch(r->r.equals("ENTERPRISE_ADMIN")||r.equals("CONTRACT_OWNER")))throw new ApiException(HttpStatus.FORBIDDEN,"CONTRACT_WRITE_FORBIDDEN","当前角色无权修改合同");return requireReadable(p,id);}
    private ContractRow requireReadable(AuthPrincipal p,Long id){if(!p.hasWorkspace())throw new ApiException(HttpStatus.FORBIDDEN,"WORKSPACE_REQUIRED","请先选择企业工作空间");ContractRow c=contracts.findDetail(id,p.tenantId());boolean global=p.roleCodes().stream().anyMatch(r->List.of("ENTERPRISE_ADMIN","CONTRACT_OWNER","FINANCE","LEGAL").contains(r));if(c==null||(!global&&!p.membershipId().equals(c.getOwnerMembershipId())&&!contracts.hasReadGrant(p.tenantId(),id,p.membershipId())&&!contracts.hasTaskAccess(p.tenantId(),id,p.membershipId())))throw new ApiException(HttpStatus.FORBIDDEN,"CONTRACT_FORBIDDEN","无权访问该合同");return c;}
    private void validate(MultipartFile f,String s){if(f==null||f.isEmpty()||f.getSize()>MAX)throw new ApiException(HttpStatus.BAD_REQUEST,"VERSION_FILE_INVALID","请上传不超过20MB的版本文件");String n=f.getOriginalFilename()==null?"":f.getOriginalFilename().toLowerCase(Locale.ROOT);if(!n.endsWith(".pdf")&&!n.endsWith(".docx"))throw new ApiException(HttpStatus.BAD_REQUEST,"VERSION_FILE_TYPE_INVALID","仅支持PDF或DOCX");if(s==null||s.isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"CHANGE_SUMMARY_REQUIRED","请填写版本变更摘要");}
    private String safe(String n){return n==null?"contract":n.replaceAll("[\\\\/:*?\"<>|]","_");}private ApiException conflict(String c,String m){return new ApiException(HttpStatus.CONFLICT,c,m);}
}

